### ISSUE TITLE
Can't get NGROK tunnel

### ISSUE THREAD

**Issue by haha4hari** [KENLIEPLAYS/FREE-RDP#2]
Can't get NGROK tunnel, be sure NGROK_AUTH_TOKEN is correct in Settings> Secrets> Repository secret. Maybe your previous VM still running: https://dashboard.ngrok.com/status/tunnels "

**Comment by KENLIEPLAYS** [comment]
try again might work

**Comment by KENLIEPLAYS** [comment]
if u still cant Try go again https://github.com/KENLIEPLAYS/FREE-RDP and fork it again

**Comment by KENLIEPLAYS** [comment]
if u still encounter this error pls follow the steps again by visiting https://github.com/KENLIEPLAYS/FREE-RDP and forking again be sure to read USAGE
